const LAST_NAME = [
  'SMITH',
  'STEWART',
  'JOHNSON',
  'SANCHEZ',
  'WILLIAMS',
  'MORRIS',
  'JONES',
  'ROGERS',
  'BROWN',
  'REED',
  'DAVIS',
  'MILLER',
  'WILSON',
  'MOORE',
  'TAYLOR',
  'ANDERSON',
  'THOMAS',
  'JACKSON',
  'WHITE',
  'HARRIS',
  'MARTIN',
  'THOMPSON',
  'GARCIA',
  'MARTINEZ',
  'ROBINSON',
  'CLARK',
  'RODRIGUEZ',
  'LEWIS',
  'LEE',
  'WALKER',
  'HALL',
  'ALLEN',
  'YOUNG',
  'HERNANDEZ',
  'KING',
  'WRIGHT',
  'COOK',
  'MORGAN',
  'BELL',
  'MURPHY',
  'BAILEY',
  'RIVERA',
  'COOPER',
  'RICHARDSON',
  'COX',
  'HOWARD',
  'WARD',
  'TORRES',
  'PETERSON',
  'GRAY',
  'RAMIREZ',
  'JAMES',
  'WATSON',
  'LOPEZ',
  'HILL',
  'GREEN',
  'ADAMS',
  'BAKER',
  'SCOTT',
  'GONZALEZ',
  'NELSON',
  'CARTER',
  'MITCHELL',
  'PEREZ',
  'ROBERTS',
  'TURNER',
  'PHILLIPS',
  'CAMPBELL',
  'PARKER',
  'EVANS',
  'EDWARDS',
  'COLLINS',
  'BROOKS',
  'KELLY',
  'SANDERS',
  'PRICE',
  'BENNETT',
  'WOOD',
  'BARNES',
  'ROSS',
  'HENDERSON',
  'COLEMAN',
  'JENKINS',
  'PERRY',
  'POWELL',
  'LONG',
  'PATTERSON',
  'HUGHES',
  'FLORES',
  'WASHINGTON',
  'BUTLER',
  'SIMMONS',
  'FOSTER',
  'GONZALES',
  'BRYANT',
  'ALEXANDER',
  'RUSSELL',
  'GRIFFIN',
  'DIAZ',
  'HAYES',
]
const FIRST_NAME = [
  'Robert',
  'Warren',
  'John',
  'Michael',
  'James',
  'Leroy',
  'William',
  'Russell',
  'Charles',
  'Leo',
  'George',
  'Andrew',
  'Joseph',
  'Edwin',
  'Richard',
  'Elmer',
  'Edward',
  'Peter',
  'Donald',
  'Floyd',
  'Thomas',
  'Lloyd',
  'Frank',
  'Ray',
  'Harold',
  'Frederick',
  'Paul',
  'Theodore',
  'Raymond',
  'Clifford',
  'Walter',
  'Vernon',
  'Jack',
  'Herman',
  'Henry ',
  'Clyde',
  'Kenneth',
  'Chester',
  'Arthur',
  'Philip',
  'Albert',
  'Alvin',
  'David',
  'Lester',
  'Harry',
  'Wayne',
  'Eugene',
  'Vincent',
  'Ralph',
  'Gordon',
  'Howard',
  'Leon',
  'Carl',
  'Lewis',
  'Willie',
  'Charlie',
  'Louis',
  'Glenn',
  'Clarence',
  'Calvin',
  'Earl',
  'Martin',
  'Roy',
  'Milton',
  'Fred',
  'Lee',
  'Joe',
  'Jesse',
  'Francis',
  'Dale',
  'Lawrence',
  'Cecil',
  'Herbert',
  'Bill',
  'Leonard',
  'Harvey',
  'Ernest',
  'Roger',
  'Alfred',
  'Victor',
  'Anthony',
  'Benjamin',
  'Stanley',
  'Wallace',
  'Norman',
  'Ronald',
  'Gerald',
  'Sam',
  'Daniel',
  'Allen',
  'Samuel',
  'Arnold',
  'Bernard',
  'Willard',
  'Billy',
  'Gilbert',
  'Melvin',
  'Edgar',
  'Marvin',
  'Oscar',
]

const OFFICER_AGE = [  //2d6
  { value: 2, age: 20 },
  { value: 3, age: 25 },
  { value: 4, age: 21 },
  { value: 5, age: 24 },
  { value: 6, age: 22 },
  { value: 7, age: 23 },
  { value: 8, age: 22 },
  { value: 9, age: 23 },
  { value: 10, age: 26 },
  { value: 11, age: 20 }, //Roll Again 1-3 (27) 4-6 (28)
  { value: 12, age: 29 },
]

const NCO_AGE = [ //2d6
  { value: 2, age: 20 }, //Roll Again 1 - 3(18) 4 - 6(19)
  { value: 3, age: 25 }, //Roll Again 1-2 (27) 3-4 (28) 5-6 (29)
  { value: 4, age: 21 }, //Roll Again 1 - 3(30) 4 - 6(31)
  { value: 5, age: 21 },
  { value: 6, age: 20 },
  { value: 7, age: 22 },
  { value: 8, age: 23 },
  { value: 9, age: 24 },
  { value: 10, age: 26 }, //Roll Again 1-3 (25) 4-6 (26)
  { value: 11, age: 20 }, //Roll Again 1-3 (32) 4-6 (33)
  { value: 12, age: 29 }, //Roll Again 1-2 (34) 3-4 (35) 5-6 (36
]

const HOME_STATE = [
  { value: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], state: 'NY' },
  { value: [11, 12, 13, 14, 15, 16, 17], state: 'PA' },
  { value: [18, 19, 20, 21, 22, 23], state: 'IL' },
  { value: [24, 25, 26, 27, 28], state: 'OH' },
  { value: [29, 30, 31, 32, 33], state: 'CA' },
  { value: [34, 35, 36, 37, 38], state: 'TX' },
  { value: [39, 40, 41, 42], state: 'MI' },
  { value: [43, 44, 45], state: 'MA' },
  { value: [46, 47, 48], state: 'NJ' },
  { value: [49, 50, 51], state: 'MO' },
  { value: [52, 53, 54], state: 'NC' },
  { value: [55, 56], state: 'IN' },
  { value: [57, 58], state: 'WI' },
  { value: [59, 60], state: 'GA' },
  { value: [61, 62], state: 'TN' },
  { value: [63, 64], state: 'KY' },
  { value: [65, 66], state: 'AL' },
  { value: [67, 68], state: 'MN' },
  { value: [69], state: 'VA' },
  { value: [70], state: 'IA' },
  { value: [71], state: 'LA' },
  { value: [72], state: 'OK' },
  { value: [73], state: 'MS' },
  { value: [74], state: 'WV' },
  { value: [75], state: 'AR' },
  { value: [76], state: 'SC' },
  { value: [77], state: 'FL' },
  { value: [78], state: 'MD' },
  { value: [79], state: 'KS' },
  { value: [80], state: 'WA' },
  { value: [81], state: 'CT' },
  { value: [82], state: 'NE' },
  { value: [83], state: 'CO' },
  { value: [84], state: 'OR' },
  { value: [85], state: 'ME' },
  { value: [86], state: 'RI' },
  { value: [87], state: 'DC' },
  { value: [88], state: 'SD' },
  { value: [89], state: 'ND' },
  { value: [90], state: 'MT' },
  { value: [91], state: 'UT' },
  { value: [92], state: 'NM' },
  { value: [93], state: 'ID' },
  { value: [94], state: 'AZ' },
  { value: [95], state: 'NH' },
  { value: [96], state: 'VT' },
  { value: [97], state: 'DE' },
  { value: [98], state: 'WY' },
  { value: [99], state: 'NV' },
  { value: [100], state: 'See comment' }, //Roll 1d6 1-3) Hawaii Territory 4) Alaska Territory 5-6) roll 1d10+1d10 again on the table above
]