const tableNoteEnum = {
  '2-13-note': require('./2-13-note.png'),
  '3-1-note': require('./3-1-note.png'),
  '3-2-note': require('./3-2-note.png'),
  '3-3-note': require('./3-3-note.png'),
  '4-1-note': require('./4-1-note.png'),
  '4-1A-note': require('./4-1A-note.png'),
  '4-2-note': require('./4-2-note.png'),
  '4-4-note': require('./4-4-note.png'),
  '4-8-note': require('./4-8-note.png'),
  '5-1-note': require('./5-1-note.png'),
  '5-2-note': require('./5-2-note.png'),
  '5-3A-note': require('./5-3A-note.png'),
  '5-3B-note': require('./5-3B-note.png'),
  '5-3C-note': require('./5-3C-note.png'),
  '5-3D-note': require('./5-3D-note.png'),
  '5-4-note': require('./5-4-note.png'),
  '5-5-note': require('./5-5-note.png'),
  '5-5A-note': require('./5-5A-note.png'),
  '5-6-note': require('./5-6-note.png'),
  '5-6A-note': require('./5-6A-note.png'),
  '5-7-note': require('./5-7-note.png'),
  '5-7A-note': require('./5-7A-note.png'),
  '5-7B-note': require('./5-7B-note.png'),
  '5-8-note': require('./5-8-note.png'),
  '5-11-note': require('./5-11-note.png'),
}

export default tableNoteEnum;